services:
  - type: web
    name: damia-cv-live
    runtime: php
    plan: free
    buildCommand: composer install --no-dev && php artisan config:cache && php artisan migrate --force
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_PORT
        value: 18464
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: APP_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PASSWORD
        sync: false
